version: 0.0
os: linux
files:
  - source: /
    destination: /web/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_flask.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_flasks.sh
      timeout: 300
      runas: root